[package]
name = "py-marc8"
version = "0.1.0"
edition = "2021"

[lib]
name = "pymarc8"
crate-type = ["cdylib"]

[dependencies]
marc8 = { path = "../marc8" }
pyo3 = { version = "0.23.3", features = ["abi3-py38"] }
